version: '3'

services:
  angular-app:
    build: ../bless-my-soul-website/
    depends_on:
      - "spring-app"
    links:
      - "spring-app"
    ports:
      - "80:80"

  spring-app:
    build: ../bless-my-soul-backend/
    ports:
      - "3000:3000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - "db"
    links:
      - "db"
    restart: unless-stopped

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
