version: '3'

services:
  angular-app:
    build: ${FRONTEND_PATH}
    restart: unless-stopped
    depends_on:
      - "spring-app"
    networks:
      - database-network
    ports:
      - "4200:4200"
    
  spring-app:
    build: ${BACKEND_PATH}
    ports:
      - "3000:3000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - "db"
    networks:
      - database-network
    restart: unless-stopped
  
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - database-network

networks:
  database-network:
    driver: bridge