version: '3'

services:
  spring-app:
    build: ${BACKEND_PATH}
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    environment:
      - server.port=${SPRING_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - "db"
    restart: unless-stopped
    networks: 
      - database-network
  
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks: 
      - database-network

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    volumes:
      - minio_storage:/data
    networks:
      - database-network
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  minio_storage: {}

networks:
  database-network:
    driver: bridge
