version: '3'

services:
  angular-app:
    build: 
      context: ${LOCAL_FRONTEND_PATH}
      dockerfile: /Dockerfile-development
    depends_on:
      - "spring-app"
    links:
      - "spring-app"
    ports:
      - "4200:4200"
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ${LOCALPATH}/src:/usr/src/app/src:cached
      - ${LOCALPATH}/e2e:/usr/src/app/e2e:cached
      - ${LOCALPATH}/tsconfig.json:/usr/src/app/tsconfig.json
      - ${LOCALPATH}/tslint.json:/usr/src/app/tslint.json
      - ${LOCALPATH}/package.json:/usr/src/app/package.json

  spring-app:
    build: ${LOCAL_BACKEND_PATH}
    ports:
      - "3000:3000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - "db"
    links:
      - "db"
    restart: unless-stopped

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
